package rasp

import "html/template"

const (
	interfacesPath     = "/etc/network/interfaces"
	interfaceWifiTempl = `# [Generated by WisebotOperator]

auto lo

iface lo inet loopback
iface eth0 inet dhcp

allow-hotplug wlan0
auto wlan0
iface wlan0 inet static
address 192.168.42.1
netmask 255.255.255.0

allow-hotplug wlan1
auto wlan1
iface wlan1 inet dhcp
    wpa-ssid "[[.ESSID]]"
    wpa-psk "[[.Password]]"
`
)

var (
	wifiConfigTemplate = template.Must(template.New("wifiTempl").Delims("[[", "]]").Parse(interfaceWifiTempl))
)
